"""Patch-only bootstrap for sea task requirements (not imported at runtime)."""

SUPPLIER_INVOICE_CODE = "SUP_INV"

SEA_TASK_REQUIREMENT_BOOTSTRAP_DOC_CODES: dict[int, list[str]] = {
	3: [],
	4: [],
	7: ["INSPECT"],
	9: ["BL", "CI", "PKL"],
	10: ["MANIFEST"],
	11: ["ENTRY"],
	12: [SUPPLIER_INVOICE_CODE],
	13: ["DO"],
	14: [SUPPLIER_INVOICE_CODE],
	16: ["FIELD"],
	17: [SUPPLIER_INVOICE_CODE],
	18: [SUPPLIER_INVOICE_CODE],
}

SEA_TASK_REQUIREMENT_BOOTSTRAP_PERMIT_APPLICATION_SEQS: frozenset[int] = frozenset({5, 15})
SEA_TASK_REQUIREMENT_BOOTSTRAP_LIGHT_PROOF_SEQS: frozenset[int] = frozenset({8, 19, 20, 21, 22, 23, 24})
SEA_TASK_REQUIREMENT_BOOTSTRAP_PERMIT_STAGES: dict[int, str] = {5: "Pre-clearance", 15: "Post-clearance"}
SEA_TASK_REQUIREMENT_BOOTSTRAP_AUTO_COMPLETE_SEQS: frozenset[int] = frozenset({1, 2})
SEA_TASK_REQUIREMENT_BOOTSTRAP_UCR_APPLICATION_SEQS: frozenset[int] = frozenset({3})
SEA_TASK_REQUIREMENT_BOOTSTRAP_FINANCE_PAYMENT_SEQS: frozenset[int] = frozenset({4, 6, 12, 14, 18})
SEA_TASK_REQUIREMENT_BOOTSTRAP_FINANCE_KIND_BY_SEQ: dict[int, str] = {
	4: "UCR",
	6: "Permit",
	12: "Standard",
	14: "Standard",
	18: "Standard",
}

# Deprecated patch aliases
DEFAULT_DOC_CODES = SEA_TASK_REQUIREMENT_BOOTSTRAP_DOC_CODES
DEFAULT_PERMIT_APPLICATION_SEQS = SEA_TASK_REQUIREMENT_BOOTSTRAP_PERMIT_APPLICATION_SEQS
DEFAULT_LIGHT_PROOF_SEQS = SEA_TASK_REQUIREMENT_BOOTSTRAP_LIGHT_PROOF_SEQS
DEFAULT_PERMIT_STAGES = SEA_TASK_REQUIREMENT_BOOTSTRAP_PERMIT_STAGES
DEFAULT_AUTO_COMPLETE_SEQS = SEA_TASK_REQUIREMENT_BOOTSTRAP_AUTO_COMPLETE_SEQS
DEFAULT_UCR_APPLICATION_SEQS = SEA_TASK_REQUIREMENT_BOOTSTRAP_UCR_APPLICATION_SEQS
DEFAULT_FINANCE_PAYMENT_SEQS = SEA_TASK_REQUIREMENT_BOOTSTRAP_FINANCE_PAYMENT_SEQS
DEFAULT_FINANCE_KIND_BY_SEQ = SEA_TASK_REQUIREMENT_BOOTSTRAP_FINANCE_KIND_BY_SEQ
