"""ERPNext Notification fixture names (see fixtures/notification.json)."""

FINANCE_PAYMENT_ACTION = "CGM Task - Finance Payment Action"
PERMIT_INVOICES_TO_FINANCE = "CGM Task - Permit Invoices to Finance"
PERMIT_RECEIPTS_FOR_DECLARANT = "CGM Task - Permit Receipts for Declarant"
PERMIT_RECEIPTS_VERIFY_FINANCE = "CGM Task - Permit Receipts Verify Finance"
UCR_INVOICE_TO_FINANCE = "CGM Task - UCR Invoice to Finance"
UCR_RECEIPT_FOR_DECLARANT = "CGM Task - UCR Receipt for Declarant"
UCR_RECEIPT_VERIFY_FINANCE = "CGM Task - UCR Receipt Verify Finance"
DAILY_STATUS_RAG_ALERT = "CGM Daily Status - RAG Alert"
